{
  parserClass="net.coleh.controlslanguageplugin.parse.ControlsParser"

  extends="com.intellij.extapi.psi.ASTWrapperPsiElement"

  psiClassPrefix="Controls"
  psiImplClassSuffix="Impl"
  psiPackage="net.coleh.controlslanguageplugin.parse"
  psiImplPackage="net.coleh.controlslanguageplugin.parse.impl"

  elementTypeHolderClass="net.coleh.controlslanguageplugin.parse.ControlsTypes"
  elementTypeClass="net.coleh.controlslanguageplugin.parse.ControlsElementType"
  tokenTypeClass="net.coleh.controlslanguageplugin.parse.ControlsTokenType"

  psiImplUtilClass="net.coleh.controlslanguageplugin.parse.ControlsPsiUtilImpl"
}

controls ::=  something*;

something ::= WHITESPACE_RANGE | PERIOD | DOES | SETS | TO | ARE | NAMED | WITH | PRIORITY | COMMA | HIGHEST | HIGHER | HIGH | NORMAL | LOW | LOWER | LOWEST |
    A_DEFAULT_OF | A_SCALE_OF | MINUS | SEMICOLON | NEWLINE | AND | THE | A | FIRST_OFF | HERES_WHAT_WILL_HAPPEN | COLON | IF | WHEN | IS | REALLY | LESS_THAN |
    MORE_THAN | THE_SAME_AS | ACTUALLY | OR | ELSE | OTHERWISE | BUT | TRULY | THEN | WHEN_NOT | IF_NOT | I_PROMISE | I_THINK | THAT | HATES | AN | MIMICS |
    CONTROLS | CONTROL | CALCULATION | SET | IT | MIGHT | HATE | ROUGHLY | EQUAL_TO | WITHIN | OF | PERCENT_SIGN | IDENTIFIER | NUMERIC_VALUE | UNKNOWN_CHARACTER
